### PR TITLE
Comments and cleanup

### PR DESCRIPTION
**Pull request by KeenWill**
Comments in OCaml? FB would never.

### CODE REVIEW

**Review by eyingxuan — APPROVED** [review]
we love docs

**Comment by KeenWill** [comment]
I shouldn't have asked for a review so fast -- I found another cleanup to do.

**Comment by KeenWill** [comment]
> I shouldn't have asked for a review so fast -- I found another cleanup to do.

Tbh that fold could be combined with the map but I'm lazy and I think it looks clean enough?

**Comment by eyingxuan** [comment]
Yea it makes sense from a readability POV

**Comment by KeenWill** [comment]
Cool

**Pull request merged**
